// (C) Uri Wilensky. https://github.com/NetLogo/Tortoise

package org.nlogo.tortoise.compiler

object ExtDefReader {
  // scalastyle:off line.size.limit
  def getAll(): Seq[String] = Seq(
    """{ "name": "codap", "prims": [ { "name": "init", "actionName": "init", "argTypes": ["command"] }, { "name": "call", "actionName": "call", "argTypes": ["wildcard"] } ] }""",

    """{ "name": "nlmap", "prims": [ { "name": "from-list", "actionName": "from-list", "argTypes": ["list"], "returnType": "wildcard" }, { "name": "to-list", "actionName": "to-list", "argTypes": ["wildcard"], "returnType": "list" }, { "name": "is-map?", "actionName": "is-map?", "argTypes": ["wildcard"], "returnType": "boolean" }, { "name": "get", "actionName": "get", "argTypes": ["wildcard", "string"], "returnType": "wildcard" }, { "name": "remove", "actionName": "remove", "argTypes": ["wildcard", "string"], "returnType": "wildcard" }, { "name": "add", "actionName": "add", "argTypes": ["wildcard", "string", "wildcard"], "returnType": "wildcard" }, { "name": "to-json", "actionName": "to-json", "argTypes": ["wildcard"], "returnType": "string" }, { "name": "to-urlenc", "actionName": "to-urlenc", "argTypes": ["wildcard"], "returnType": "string" }, { "name": "from-json", "actionName": "from-json", "argTypes": ["string"], "returnType": "wildcard" } ] }""",

    """{ "name": "logging", "prims": [ { "name": "all-logs", "actionName": "all-logs", "argTypes": [], "returnType": "list" }, { "name": "clear-logs", "actionName": "clear-logs", "argTypes": [], "returnType": "unit" }, { "name": "log-globals", "actionName": "log-globals", "argTypes": [{ "type": "string", "isRepeatable": true }], "returnType": "unit" }, { "name": "log-message", "actionName": "log-message", "argTypes": ["string"], "returnType": "unit" } ] }""",

    """{"name":"gbcc","prims":[{"name":"set","actionName":"set","argTypes":["string","wildcard"]},{"name":"get","actionName":"get","argTypes":["string"],"returnType":"wildcard"},{"name":"get-from-user","actionName":"get-from-user","argTypes":["string","string"],"returnType":"wildcard"},{"name":"store-globals","actionName":"store-globals","argTypes":[]},{"name":"restore-globals","actionName":"retore-globals","argTypes":[]},{"name":"restore-globals-from-user","actionName":"restore-globals-from-user","argTypes":["string"]},{"name":"broadcast-to-gallery","actionName":"broadcast-to-gallery","argTypes":["string","string"]},{"name":"compile-observer-code","actionName":"compile-observer-code","argTypes":["string","string"]},{"name":"compile-turtle-code","actionName":"compile-turtle-code","argTypes":["number","string","string"]},{"name":"compile-patch-code","actionName":"compile-patch-code","argTypes":["number","number","string","string"]},{"name":"run-observer-code","actionName":"run-observer-code","argTypes":["string"]},{"name":"run-turtle-code","actionName":"run-turtle-code","argTypes":["number","string"]},{"name":"run-patch-code","actionName":"run-patch-code","argTypes":["number","number","string"]}]}""",

    """{"name":"graph","prims":[{"name":"equation","actionName":"equation","argTypes":["string","number","number","number","number","number","number","number","number","number"],"returnType":"list"},{"name":"create-point","actionName":"create-point","argTypes":["string","list"]},{"name":"update-point","actionName":"update-point","argTypes":["string","list"]},{"name":"delete-point","actionName":"delete-point","argTypes":["string"]},{"name":"get-point","actionName":"get-point","argTypes":["string"],"returnType":"list"},{"name":"import","actionName":"import","argTypes":["list"]},{"name":"eval-command","actionName":"eval-command","argTypes":["string"]},{"name":"eval-command-get-labels","actionName":"eval-command-get-labels","argTypes":["string"],"returnType":"string"},{"name":"eval-command-cas","actionName":"eval-command-cas","argTypes":["string"],"returnType":"string"},{"name":"set-point-xy","actionName":"set-point-xy","argTypes":["string","list"]},{"name":"get-point-xy","actionName":"get-point-xy","argTypes":["string"],"returnType":"list"},{"name":"set-point-gxy","actionName":"set-point-gxy","argTypes":["string","list"]},{"name":"get-point-gxy","actionName":"get-point-gxy","argTypes":["string"],"returnType":"list"}]}""",

    """{"name":"maps","prims":[{"name":"create-marker","actionName":"create-marker","argTypes":["string","list"]},{"name":"set-marker-xy","actionName":"set-marker-xy","argTypes":["string","list"]},{"name":"set-marker-lng-lat","actionName":"set-marker-lng-lat","argTypes":["string","list"]},{"name":"delete-marker","actionName":"delete-marker","argTypes":["string"]},{"name":"get-marker-xy","actionName":"get-marker-xy","argTypes":["string"],"returnType":"list"},{"name":"get-marker-lng-lat","actionName":"get-marker-lng-lat","argTypes":["string"],"returnType":"list"},{"name":"import","actionName":"import","argTypes":["list"]},{"name":"export","actionName":"import","argTypes":[],"returnType":"list"}]}""",

    """{"name":"physics","prims":[{"name":"create-object","actionName":"create-object","argTypes":["string","list"]},{"name":"delete-object","actionName":"delete-object","argTypes":["string"]},{"name":"get-object","actionName":"get-object","argTypes":["string"],"returnType":"list"},{"name":"connect-to-turtle","actionName":"connect-to-turtle","argTypes":["string","number"]},{"name":"disconnect-from-turtle","actionName":"disconnect-from-turtle","argTypes":["string","number"]},{"name":"import","actionName":"import","argTypes":["list"]}]}""",

    """{"name":"image","prims":[{"name":"import","actionName":"import","argTypes":["string"]},{"name":"zoom","actionName":"zoom","argTypes":["number"]},{"name":"reset-zoom","actionName":"reset-zoom","argTypes":[ ]},{"name":"import-pcolors","actionName":"import-pcolors","argTypes":["string"]},{"name":"clear","actionName":"clear","argTypes":[]}]}"""

  )
  // scalastyle:on line.size.limit
}
